title: Ifan Jaya Suswanto Zalukhu
description: Senior C# .NET Backend Engineer | AWS Community Builder | AI & Workflow Automation Enthusiast
url: "https://www.ifanzalukhu97.com"
baseurl: ""

collections:
  slides:
    output: false
    sort_by: date

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - job-logs.txt
  - .kiro
